# Reusable workflow to build a Node app.

name: Build

on:
  workflow_call:
    inputs:
      artifactName:
        required: true
        type: string
      node_version:
        required: true
        type: string

jobs:
  build:
    name: Build and test a Node app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for other jobs
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifactName }}
        path: .

    - name: Add job summary
      run: |
        echo '### Node app built and tested :hammer_and_wrench:' >> $GITHUB_STEP_SUMMARY
        echo 'Run URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}' >> $GITHUB_STEP_SUMMARY

  summary:
    name: Final summary
    runs-on: ubuntu-latest
    steps:
    - name: Add job summary
      run: |
        echo '### Build complete' >> $GITHUB_STEP_SUMMARY
        
