# Reusable workflow to build and publish a container to ACR.

name: Publish Container to ACR

on:
  workflow_call:
    inputs:
      artifactName:
        required: true
        type: string
      acrName:
        required: true
        type: string
      tagName:
        required: true 
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
    outputs:
      imageName:
        type: string
        value: ${{ steps.publish.outputs.imageName }}

jobs:
  publish:
    name: Publish container to ACR
    permissions:
      contents: none
    runs-on: ubuntu-latest
    outputs:
      imageName: ${{ steps.push-container.outputs.imageName }}

    steps:
    - name: Download artifact from the build job
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifactName }}

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push container to an Azure Container Registry
      id: push-container
      run: |
        az acr login --name ${{ inputs.acrName }}
        docker build . -t ${{ inputs.tagName }}
        docker tag ${{ inputs.tagName }} ${{ inputs.acrName }}.azurecr.io/${{ inputs.tagName }}:${{ github.sha }}
        echo "imageName=${{ inputs.acrName }}.azurecr.io/${{ inputs.tagName }}:${{ github.sha }}" >> $GITHUB_OUTPUT
        docker push ${{ inputs.acrName }}.azurecr.io/${{ inputs.tagName }}:${{ github.sha }}
    
#    - name: Publish summary
#      run: echo '### Container published to ${{ inputs.acrName }}.azurecr.io/${{ inputs.tagName }}:${{ github.sha }} :dart:' >> $GITHUB_STEP_SUMMARY