# Orchestrating workflow to build and deploy a Node.js application to an Azure App Service

name: Deploy

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

env:
  ARTIFACT_NAME: 'gd-simple-node-app'

jobs:
  build:
    name: 'Build'
    uses: gidavies-org/deployer/.github/workflows/build.yml@main
    with:
        artifactName: '$ARTIFACT_NAME'
        node_version: '16.x'
  
  publish:
    name: 'Publish to ACR'
    uses: gidavies-org/deployer/.github/workflows/container-publish.yml@main
    with:
      artifactName: '$ARTIFACT_NAME'
      acrName: 'simplewebapp'
      tagName: 'simplewebapp-gd'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

    needs: build

  deploy-dev:
    # Don't run this job if the commit message contains 'skip deploy'
    if: "!contains(github.event.head_commit.message, 'skip deploy')"
    name: 'Deploy to Dev'
    uses: gidavies-org/deployer/.github/workflows/deploy-with-secrets.yml@main
    with:
      envName: 'Dev'
      appServiceName: 'simplewebapp-gd-dev'
      imageName: ${{ needs.publish.outputs.imageName}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

    needs: publish

  deploy-test:
    # Don't run this job if the commit message contains 'skip deploy'
    if: "!contains(github.event.head_commit.message, 'skip deploy')"
    name: 'Deploy to Test'
    uses: gidavies-org/deployer/.github/workflows/deploy-with-keyvault.yml@main
    with:
      envName: 'Test'
      appServiceName: 'simplewebapp-gd-test'
      imageName: ${{ needs.publish.outputs.imageName}}
    secrets:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    needs: deploy-dev

  deploy-prod:
    # Don't run this job if the commit message contains 'skip deploy'
    if: "!contains(github.event.head_commit.message, 'skip deploy')"
    name: 'Deploy to Prod'
    uses: gidavies-org/deployer/.github/workflows/deploy-with-oidc.yml@main
    with:
      envName: 'Prod'
      appServiceName: 'simplewebapp-gd-prod'
      imageName: ${{ needs.publish.outputs.imageName}}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    needs: deploy-dev