# Workflow to build and deploy a Node.js application to an Azure App Service

name: Deploy

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    uses: gidavies-org/deployer/.github/workflows/build.yml@main
    with:
      node_version: '16.x'

  deploy-dev:
     # Don't run this job if the commit message contains 'skip deploy'
    if: "!contains(github.event.head_commit.message, 'skip deploy')"
    uses: gidavies-org/deployer/.github/workflows/deploy-with-secrets.yml@main
    with:
      envName: 'Dev'
      appServiceName: 'simplewebapp-gd-dev'
      acrName: 'simplewebapp'
      tagName: 'simplewebapp-gd'
    secrets:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

    needs: build