# Reusable workflow to deploy a Node app to an Azure App Service using GitHub Secrets.

name: Deploy with secrets

on:
  workflow_call:
    inputs:
      artifactName:
        required: true
        type: string
      envName:
        required: true
        type: string
      appServiceName:
        required: true
        type: string
      acrName:
        required: true
        type: string
      tagName:
        required: true 
        type: string
      imageName:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  deploy:
    name: Deploy to ${{ inputs.envName }}
    permissions:
      contents: none
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.envName }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy container from ACR to Azure App Service
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ inputs.appServiceName }}
        images: '${{ inputs.imageName }}'
      
    - name: Deployment summary
      run: echo '### Deployment to ${{ inputs.envName }} complete. Container ${{ inputs.imageName }} deployed to App Service ${{ inputs.appServiceName }} :dart:' >> $GITHUB_STEP_SUMMARY