# Workflow to build and deploy a Node.js application to an Azure App Service

name: Deploy

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

env:
  ARTIFACT_NAME: 'gd-simple-node-app'

jobs:
  build:
    uses: gidavies-org/deployer/.github/workflows/build.yml@main
    with:
        artifactName: '$ARTIFACT_NAME'
        node_version: '16.x'

  deploy-dev:
    # Don't run this job if the commit message contains 'skip deploy'
    if: "!contains(github.event.head_commit.message, 'skip deploy')"
    uses: gidavies-org/deployer/.github/workflows/deploy-with-secrets.yml@main
    with:
      envName: 'Dev'
      artifactName: '$ARTIFACT_NAME'
      appServiceName: 'simplewebapp-gd-dev'
      acrName: 'simplewebapp'
      tagName: 'simplewebapp-gd'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

    needs: build

  deploy-prod:
    # Don't run this job if the commit message contains 'skip deploy'
    if: "!contains(github.event.head_commit.message, 'skip deploy')"
    uses: gidavies-org/deployer/.github/workflows/deploy-with-oidc.yml@main
    with:
      envName: 'Dev'
      artifactName: '$ARTIFACT_NAME'
      appServiceName: 'simplewebapp-gd-prod'
      acrName: 'simplewebapp'
      tagName: 'simplewebapp-gd'
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    needs: deploy-dev